// Assembles the Capacitor web bundle from web/public.
//
// There is no bundler in this project: web/public/*.js are raw ES modules that
// import each other relatively and are served at /assets by express.static. A
// Capacitor bundle has no server and no EJS, so the job here is to reproduce
// that directory as a plain static site whose every path is relative.
//
// The key decision: files land at the bundle ROOT, not under an /assets folder.
// That keeps every "./ui.js" import correct without rewriting a single import.
import { cp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(root, "web", "public");
const views = join(root, "web", "views");
const out = join(root, "dist-mobile");
// Where the bundled app sends its API calls. The bundle is not same-origin with
// the server, so this has to be absolute and baked in at build time.
const apiBase = (
  process.env.WORKORDER_API_BASE || "https://work-order-eta.vercel.app"
).replace(/\/$/, "");
// Absolute /assets/... references only make sense behind express.static. In the
// bundle the same files sit next to the page, so they become relative.
// Vercel Web Analytics is injected by the host at /_vercel/... — a path that
// exists on the deployment and nowhere inside an app bundle. Drop it rather
// than ship a script tag that 404s on every launch.
const relative = (html) =>
  html
    .replace(/(["'(])\/assets\//g, "$1./")
    .replace(/(["'])\/mark\.svg/g, "$1./mark.svg")
    .replace(/\s*<script[^>]*\/_vercel\/[^>]*><\/script>/g, "")
    .replace(/\s*<script>\s*window\.va\s*=[\s\S]*?<\/script>/g, "");
// The console shell is an EJS template on the web. Only <%= title %> is dynamic,
// so rendering it here avoids shipping an EJS runtime into the app.
async function page(file, title) {
  const html = await readFile(join(views, file), "utf8");
  return relative(html.replaceAll("<%= title %>", title));
}
// Stamped into the bundle so native.js can find the server. Kept as its own
// file rather than an inline <script> so the page's CSP stays simple.
const config = `// Generated by scripts/build-mobile.mjs — do not edit.
globalThis.__WORKORDER_API_BASE__ = ${JSON.stringify(apiBase)};
globalThis.__WORKORDER_CLIENT_VERSION__ = ${JSON.stringify(
  JSON.parse(await readFile(join(root, "package.json"), "utf8")).version,
)};
`;
await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });
// Everything the web console serves, minus the service worker, which registers
// against a real origin and has nothing to do inside a bundle.
await cp(source, out, {
  recursive: true,
  filter: (path) => !path.endsWith("field-sw.js") && !path.endsWith("sw.js"),
});
await writeFile(join(out, "workorder-config.js"), config);
const inject = (html) =>
  html.replace(
    "</head>",
    '  <script src="./workorder-config.js"></script>\n</head>',
  );
await writeFile(
  join(out, "index.html"),
  inject(await page("index.ejs", "WorkOrder")),
);
// field.html is a second entry point and already static; it only needs the
// same path rewrite so it works from the bundle root.
await writeFile(
  join(out, "field.html"),
  inject(relative(await readFile(join(source, "field.html"), "utf8"))),
);
// A bundled page that still asks for an absolute server path would 404 against
// the app bundle instead of the API, and it would do so silently.
const offenders = [];
for (const name of await readdir(out)) {
  const file = join(out, name);
  if (name.endsWith(".html")) {
    const html = await readFile(file, "utf8");
    for (const match of html.matchAll(/(?:src|href)="(\/[^/][^"]*)"/g))
      offenders.push(`${name}: ${match[1]}`);
    // native.js is the one module allowed to name /assets/: assetUrl() is what
    // hands every other module the right path for the environment it is in.
  } else if (name.endsWith(".js") && name !== "native.js") {
    // Markup built inside a module is invisible to the HTML rewrite above, so
    // an /assets/... string here would 404 at runtime with nothing to show for
    // it. Modules should ask native.js for assetUrl()/homeHref() instead.
    const js = await readFile(file, "utf8");
    if (js.includes("/assets/")) offenders.push(`${name}: /assets/ reference`);
  }
}
if (offenders.length)
  throw new Error(
    `Absolute paths survived the bundle and would 404 in the app:\n  ${offenders.join("\n  ")}`,
  );
console.log(`Mobile bundle written to ${out}`);
console.log(`API base: ${apiBase}`);
